### ISSUE TITLE
Imported playlists have no songs in them.

### ISSUE THREAD

**Issue by Minuano2993** [cromaguy/Rhythm#103]
As the title says, imported playlists have no songs in them despite said songs being available in the same location as the playlist directs. 

Format: M3U

**Comment by cromaguy** [comment]
# Hi there! # 

**Thanks for reporting, the issue has been resolved and you will get the fix eventually during next Beta releases followed by Rhythm 3 release!** 
Sorry for inconvenience :(

**Comment by cromaguy** [comment]
# Hi there! # 

**The fixes are now live with the latest Stable release! Check if your reported issues are resolved or not and lemme know ;)**

Thank you

**Comment by Minuano2993** [comment]
Hi, the same issue still occurs on the latest stable update.

at first, I tried with 2 different m3u playlist formats one of them where it states partial path "/Music/filename" and the other would state the full file path "storage/emulated/0/Music/filename" (be mindful that the m3u file is in the same directory as the songs so there shouldn't be any issues with importing playlists that have partial paths.)

**Comment by Minuano2993** [comment]
Hi. I am not sure what happened but it's suddenly fixed on the new stable release. Works like a charm now. Thank You.

**Comment by cromaguy** [comment]
# Hey there! # 

I forgot to mention it here but the issues were addressed in the latest 3.3 Stable build!
Thank you for waiting ;)
