### ISSUE TITLE
3.8.292.815 introduced proprietary libraries

### ISSUE THREAD

**Issue by IzzySoft** [cromaguy/Rhythm#149]
Looks like something dragged in Firebase, and with it Google Mobile Services – and I'm afraid that "something" is proprietary itself and called "Google Cast". As your release notes do not mention this, I assume this was not intended – so can you please take care to get it out again?

At IzzyOnDroid, we've just rolled back this update, and temporarily disabled the daily update check for Rhythm (so this release does not get pulled in again right away). We'll enable it again as soon as this issue is solved. Thanks for your help with that!

**Comment by cromaguy** [comment]
# Hi there Izzy! # 

> Looks like something dragged in Firebase, and with it Google Mobile Services – and I'm afraid that "something" is proprietary itself and called "Google Cast". As your release notes do not mention this, I assume this was not intended – so can you please take care to get it out again?

Yes I was um, tryin to implement Cast which was incomplete, but I completely missed that it was against the rules so um, I reverted and removed the half-baked cast implementation....

> At IzzyOnDroid, we've just rolled back this update, and temporarily disabled the daily update check for Rhythm (so this release does not get pulled in again right away). We'll enable it again as soon as this issue is solved. Thanks for your help with that!

This issue is resolved so lemme create a new release with few patches so that the right release is being picked up hehe...

Thank you & Happy Holidays Izzy🎄

**Comment by IzzySoft** [comment]
Thanks, confirming the issue solved! 🥳 Offenders gone, APK reproducible. So updates re-enabled, the current one already added at our staging server – all ready for the jingles at the… "extremely illuminated coniferous tree with religious background" 🙊 💨 Err… Happy holidays for you, too – and may they bring light (which seems to be the common denominator with all the holidays of the season I'm aware of: the Jewish Chanukkah, Christmas, and the Nordic Festival of Lights)! One more day to winter solstice, while we're at it, from which on more light returns – hah! The Jul Festival, also with lights and fire… May whatever jingle bells bring warmth and light to your hearts!

**Comment by IzzySoft** [comment]
Sorry, I have to take that back:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Cast (/com/google/android/gms/cast): NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp

4 offenders.
```

I had just looked at the import log, which didn't mention that. The scanner still shows them 😢

**Comment by cromaguy** [comment]
# I added a Commit to remove that dependency.... #

Check again now..

But unfortunately I am out of station due to holidays and its not possible to do a new release again, so please try to get it back to stores ASAP because people using Rhythm from IzzyOnDroid are still stuck on an old build from 4 days back....

Its holidays and I can't give anymore time...

**Comment by IzzySoft** [comment]
> I added a Commit to remove that dependency....

Thanks! But we'll need an APK…

> please try to get it back to stores ASAP

Sorry, we cannot put a version up that's not meeting our inclusion criteria. As soon as a fixed one is available, we'll send it out of course (and 4 days is not that big a gap). And yeah, we'll be on "holiday break" as well a bit. Enjoy yours!

**Comment by cromaguy** [comment]
Will build again then but with the same changelog?

**Comment by cromaguy** [comment]
# New Stable Release #

Created a new Stable Release, please check again for any issues..
[3.8 Release](https://github.com/cromaguy/Rhythm/releases/tag/v3.8.293.818-stable)

**Comment by IzzySoft** [comment]
> No offending libs found.

This time I've checked twice to make sure, and you succeeded. Enjoy the holidays now 🤗
