### ISSUE TITLE
Not able to play all songs in a random order 

### ISSUE THREAD

**Issue by devSJR** [cromaguy/Rhythm#74]
First of all, this app is awesome. This is one of a kind. I have never seen a concept like this in a local app. It feels like my own Music platform locally on my smartphone. 

But here is my issue. I'm not smart enough to figure out how to play all my songs or even the songs in a random fashion. I only see some songs like in lists of six. To be clear, the app plays songs and I can select some songs from playlists. But I'm not able to play my entire library without doing anything like playlist creation before. Is there a way to do it?

**Comment by cromaguy** [comment]
@devSJR Library>Songs>Play All/Shuffle

**Comment by devSJR** [comment]
Thanks for the fast response. I tried that before I erased this issue here and I even completely cleaned the cache and storage of the app and gave again all the permissions. but once I try to play songs the app gets totally unresponsive and I get the error message. The options I have is to wait, which does nothing, it seems, or to close the app.

**Comment by cromaguy** [comment]
Can you show me the error? Because I couldn't reproduce your issue...

**Comment by devSJR** [comment]
I certainly can do that, but it's actually just the normal Android message that asks to either wait or close the app because the app is not responding.
The entire app becomes unresponsive.
If I use any other play mode like those suggested by Mood and Moments, it works perfectly. 
I don't want to waste your precious time. Is there by chance a version with a debugging option so that I could provide you with a log?

**Comment by greNinja007** [comment]
I also have a pretty similar problem, after selecting to shuffle my library and create a queue, but as the shuffle is enabled it is not playing the next song but completely different song and changing the queue again and again. I don't know is this the intended feature or not.

**Comment by devSJR** [comment]
I just noticed something interesting. If I select, for example, play only short songs or songs with a specific length, they are indeed played and they are played in random order, but not the entry with "play all". Maybe this helps you a bit.

**Comment by cromaguy** [comment]
# Hey there! # 

**Your reported issues are now fixed in the new Rhythm 2.9 Stable update, which is now live! 🚀**

**Comment by devSJR** [comment]
I'm using the latest stable version and I am sorry to tell you that the issue is not solved for me. As I stated, I can play songs, for example short songs or songs within 3 to 5 minutes or longer songs, but I cannot play all songs if I do this with the app crashes.

**Comment by devSJR** [comment]
Hello,

This is the error message that I received now. As usual, I start the app, go to Songs and then hit the Random button or the Play button and then it does nothing. It doesn't happen if I use the filtered songs with a certain duration. 

Thanks for enabling this interface. 

Happy Diwali


java.lang.RuntimeException: Unable to create service chromahub.rhythm.app.service.MediaPlaybackService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service chromahub.rhythm.app/.service.MediaPlaybackService
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5148)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2547)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service chromahub.rhythm.app/.service.MediaPlaybackService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5094)
	at android.os.Parcel.readParcelable(Parcel.java:5076)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3256)
	at android.os.Parcel.createException(Parcel.java:3245)
	at android.os.Parcel.readException(Parcel.java:3228)
	at android.os.Parcel.readException(Parcel.java:3170)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7268)
	at android.app.Service.startForeground(Service.java:776)
	at chromahub.rhythm.app.service.MediaPlaybackService.startForegroundWithNotification(MediaPlaybackService.kt:248)
	at chromahub.rhythm.app.service.MediaPlaybackService.onCreate(MediaPlaybackService.kt:180)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5135)
	... 9 more
